### PR TITLE
Support KiCAD 8.0

### PR DESCRIPTION
**Pull request by gauravmm**
Here's what needs to be done to support KiCAD 8:

- [X] `GetSheetfile` and `GetSheetname` (Thanks @OfficialDyray)
- [X] Update `FP_TEXT` to `PCB_FIELD` (Thanks @OfficialDyray)
- [x] `nets.AppendNet` in `find_or_set_net`

### CODE REVIEW

**Comment by gauravmm** [comment]
I can't figure out how to add a net to the API, or even if I need to bother at all. I'll  run some experiments and then decide, but if you know something about this let me know.

**Comment by OfficialDyray** [comment]
I feel like adding Nets to the PCB shouldn't be necessary. Won't all the Nets we need exist from importing the schematic footprints? Also- Thanks you for taking the time to write this plugin, I have found it very useful.

**Comment by gauravmm** [comment]
I think its used to associate traces with nets. I've no idea if KiCAD will infer the nets automatically, or something else.

**Comment by OfficialDyray** [comment]
**Under kicad 6.0** 
nets.AppendNet() appears to add a new net to the board/NETINFO_LIST: 
```
>> import pcbnew
>> board = pcbnew.GetBoard()
>> nets = board.GetNetInfo()
>> newNet = pcbnew.NETINFO_ITEM(board)
>> newNet.SetNetname("test");

>> board.GetNetCount()
1

>> nets.AppendNet(newNet)
>> board.GetNetCount()
2
```
**Under kicad 8.0**
I'm not sure how to add a net to the [NETINFO_LIST](https://docs.kicad.org/doxygen-python-8.0/classpcbnew_1_1NETINFO__LIST.html) or even if its possible in 8.0.

One option is to just return the Default (Unassigned) net so that Kicad can figure out how to deal with it: `board.GetNetsByNetcode()[0]`
or
`nets.NetsByNetcode()[0]`

**Comment by gauravmm** [comment]
I'll take a look at this soon, sorry about the delay. Thanks for figuring this out!

**Comment by gauravmm** [comment]
> We could just return the <no net> net: `board.FindNet(0)`

That works great! Thanks for figuring this out, I'll merge this to master now.

**Pull request closed without merging**
