### PR TITLE
Fix Filled Area/Zone not copying

### PR DESCRIPTION
**Pull request by i404788**
* Adds support for Fill Areas/Zones
* Fixes via nets not always matching
* Fixes arc mid point not being transformed resulting in straight lines usually
* Fixes net issues with areas/vias

### CODE REVIEW

**Comment by i404788** [comment]
:+1:, Note there is still a known issue that I'm working on with Named Areas having /<Net> while pads/traces have /<Subboard>/<Net> meaning they will seperate when recalculating fills.

**Comment by gauravmm** [comment]
Hey, thanks for the pull request! I've made some small changes and pushed my version up to branch `pullreq4`. Could you please merge those into your `master` branch and make changes based on that?

I have a question: do we need to clear `Area` objects in `clear_traces`? (Also, can area objects be members of groups?)

Once again, thanks for the help!

**Comment by i404788** [comment]
I believe the Area would duplicate when regenerating if not in `clear_traces`. Also they can indeed be members of groups.
I'll merge you changes.

**Comment by gauravmm** [comment]
Thank you for the pull request!

**Pull request merged**
